version: "3"

# Taskfile for WhatsApp API Project
# Install Task: https://taskfile.dev/installation/
# Usage: task [command]

vars:
  SERVER_DIR: apps/server
  WEB_DIR: apps/web
  SERVER_PORT: 8080
  WEB_PORT: 5173

tasks:
  # ============================================================================
  # Development Tasks
  # ============================================================================

  dev:
    desc: "Start both backend and frontend in development mode"
    deps:
      - dev:backend
      - dev:frontend

  dev:backend:
    desc: "Start Go backend server in development mode"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🚀 Starting backend server on port {{.SERVER_PORT}}..."
      - go run cmd/whatsapp/main.go
    silent: false

  dev:frontend:
    desc: "Start React frontend dev server"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🚀 Starting frontend dev server on port {{.WEB_PORT}}..."
      - npm run dev
    silent: false

  # ============================================================================
  # Build Tasks
  # ============================================================================

  build:
    desc: "Build both backend and frontend for production"
    cmds:
      - task: build:backend
      - task: build:frontend

  build:backend:
    desc: "Build Go backend binary"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🔨 Building backend..."
      - go build -o ../../bin/whatsapp-server cmd/whatsapp/main.go
      - echo "✅ Backend built successfully bin/whatsapp-server"

  build:frontend:
    desc: "Build React frontend for production"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🔨 Building frontend..."
      - npm run build
      - echo "✅ Frontend built successfully in apps/web/dist"

  # ============================================================================
  # Install Dependencies
  # ============================================================================

  install:
    desc: "Install all dependencies (backend and frontend)"
    cmds:
      - task: install:backend
      - task: install:frontend

  install:backend:
    desc: "Install Go dependencies"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "📦 Installing Go dependencies..."
      - go mod download
      - go mod tidy
      - echo "✅ Go dependencies installed"

  install:frontend:
    desc: "Install npm dependencies"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "📦 Installing npm dependencies..."
      - npm install
      - echo "✅ npm dependencies installed"

  # ============================================================================
  # Testing Tasks
  # ============================================================================

  test:
    desc: "Run all tests (backend and frontend)"
    cmds:
      - task: test:backend
      - task: test:frontend

  test:backend:
    desc: "Run Go tests"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🧪 Running backend tests..."
      - go test ./... -v

  test:backend:coverage:
    desc: "Run Go tests with coverage"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🧪 Running backend tests with coverage..."
      - go test ./... -coverprofile=coverage.out
      - go tool cover -html=coverage.out -o coverage.html
      - echo "✅ Coverage report generated in apps/server/coverage.html"

  test:frontend:
    desc: "Run frontend tests"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🧪 Running frontend tests..."
      - npm run test

  # ============================================================================
  # Linting & Formatting
  # ============================================================================

  lint:
    desc: "Lint all code (backend and frontend)"
    cmds:
      - task: lint:backend
      - task: lint:frontend

  lint:backend:
    desc: "Lint Go code"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🔍 Linting backend code..."
      - go vet ./...
      - go fmt ./...
      - echo "✅ Backend linting complete"

  lint:frontend:
    desc: "Lint frontend code"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🔍 Linting frontend code..."
      - npm run lint
      - echo "✅ Frontend linting complete"

  # ============================================================================
  # Database Tasks
  # ============================================================================

  db:migrate:
    desc: "Run database migrations"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🗄️  Running database migrations..."
      - go run cmd/whatsapp/main.go migrate
      - echo "✅ Migrations complete"

  db:reset:
    desc: "Reset database (WARNING: Deletes all data)"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "⚠️  WARNING - This will delete all data"
      - cmd: |
          read -p "Are you sure? (yes/no): " confirm
          if [ "$confirm" = "yes" ]; then
            rm -f /data/whatsmeow.db
            echo "✅ Database reset complete"
          else
            echo "❌ Database reset cancelled"
          fi
    platforms: [linux, darwin]

  db:reset:windows:
    desc: "Reset database on Windows (WARNING: Deletes all data)"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "⚠️  WARNING - This will delete all data"
      - cmd: |
          $confirm = Read-Host "Are you sure? (yes/no)"
          if ($confirm -eq "yes") {
            Remove-Item -Path "/data/whatsmeow.db" -Force -ErrorAction SilentlyContinue
            Write-Host "✅ Database reset complete"
          } else {
            Write-Host "❌ Database reset cancelled"
          }
    platforms: [windows]

  # ============================================================================
  # Cleanup Tasks
  # ============================================================================

  clean:
    desc: "Clean all build artifacts and dependencies"
    cmds:
      - task: clean:backend
      - task: clean:frontend

  clean:backend:
    desc: "Clean Go build artifacts"
    dir: "{{.SERVER_DIR}}"
    cmds:
      - echo "🧹 Cleaning backend artifacts..."
      - go clean
      - rm -rf bin/
      - echo "✅ Backend cleaned"

  clean:frontend:
    desc: "Clean frontend build artifacts"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🧹 Cleaning frontend artifacts..."
      - rm -rf dist/
      - rm -rf node_modules/
      - echo "✅ Frontend cleaned"

  # ============================================================================
  # Docker Tasks
  # ============================================================================

  docker:up:
    desc: "Start Docker containers"
    cmds:
      - echo "🐳 Starting Docker containers..."
      - docker-compose up -d
      - echo "✅ Docker containers started"

  docker:down:
    desc: "Stop Docker containers"
    cmds:
      - echo "🐳 Stopping Docker containers..."
      - docker-compose down
      - echo "✅ Docker containers stopped"

  docker:logs:
    desc: "View Docker container logs"
    cmds:
      - docker-compose logs -f

  docker:build:
    desc: "Build Docker images"
    cmds:
      - echo "🐳 Building Docker images..."
      - docker-compose build
      - echo "✅ Docker images built"

  # ============================================================================
  # Production Tasks
  # ============================================================================

  prod:start:
    desc: "Start production servers"
    cmds:
      - echo "🚀 Starting production servers..."
      - task: prod:backend &
      - task: prod:frontend &

  prod:backend:
    desc: "Start production backend server"
    cmds:
      - echo "🚀 Starting production backend..."
      - ./bin/whatsapp-server

  prod:frontend:
    desc: "Serve production frontend"
    dir: "{{.WEB_DIR}}"
    cmds:
      - echo "🚀 Starting production frontend..."
      - npm run preview

  # ============================================================================
  # Utility Tasks
  # ============================================================================

  setup:
    desc: "Initial project setup (install dependencies and build)"
    cmds:
      - echo "🔧 Setting up project..."
      - task: install
      - task: build
      - echo "✅ Project setup complete!"

  check:
    desc: "Run all checks (lint, test, build)"
    cmds:
      - echo "🔍 Running all checks..."
      - task: lint
      - task: test
      - task: build
      - echo "✅ All checks passed!"

  status:
    desc: "Check status of running services"
    cmds:
      - echo "📊 Checking service status..."
      - cmd: |
          echo "Backend (port {{.SERVER_PORT}})"
          curl -s http://localhost:{{.SERVER_PORT}}/health || echo "  ❌ Not running"
          echo ""
          echo "Frontend (port {{.WEB_PORT}})"
          curl -s http://localhost:{{.WEB_PORT}} > /dev/null && echo "  ✅ Running" || echo "  ❌ Not running"

  logs:
    desc: "View application logs"
    cmds:
      - echo "📋 Viewing logs..."
      - tail -f apps/server/logs/*.log

  # ============================================================================
  # Help
  # ============================================================================

  default:
    desc: "Show available tasks"
    cmds:
      - task --list

  help:
    desc: "Show detailed help information"
    cmds:
      - echo "📚 WhatsApp API Taskfile Help"
      - echo ""
      - echo "Common Commands"
      - echo "  task dev              - Start both backend and frontend in dev mode"
      - echo "  task dev:backend      - Start only backend server"
      - echo "  task dev:frontend     - Start only frontend server"
      - echo "  task build            - Build both backend and frontend"
      - echo "  task test             - Run all tests"
      - echo "  task lint             - Lint all code"
      - echo "  task setup            - Initial project setup"
      - echo "  task check            - Run all checks (lint, test, build)"
      - echo ""
      - echo "For full list of tasks, run task --list"
